### ISSUE TITLE
Feature: better CI support

### ISSUE THREAD

**Issue by hlb** [InfuseAI/piperider#311]
> Users can run PipeRider through the CI process, so users can get reports instantly when code/schema changes, pipelines are executed, or perform data quality checks periodically.

Users can use PipeRider to generate report files, but it was hard before to get the latest report files from the command line interface and perform follow-up actions in the CI automation process.

By implementing this feature, users can use PipeRider to:

- get the location of output files of reports or comparisons
- compare the most recent two reports easily

So users can upload the generated reports to AWS S3, send notifications to Slack, and perform other actions by using tools through the CI process.

# Feature Design

## Requirement

- Users can get the location of output files of reports or comparisons.
- Users can compare the most recent two reports without providing any input. (It is more convenient, and users don’t need to know how PipeRider works internally)
- We can track if a report is generated by CI.

## Non-goals

- upload files for users. They should be able to upload via the tools they use.
- send notifications for users. They should be able to send notifications via webhook or other tools.

## Use Cases

- Users can get reports instantly when code/schema changed, pipeline executed, or perform data quality check periodically.
- Users can collect all reports in one place.
- Data consumers can check the reports without running PipeRider or gaining data access.

## User Journeys

- User can use `piperider generate-report -o $PATH` to get the location of output.
- User can use `piperider compare-reports --last` to generate a comparison report with the most recent two reports.

----

# Milestones
- [x] Users can get the location of output files of reports or comparisons.
- [x] Users can compare the most recent two reports without providing any input.
- [x] Track if a report is generated by CI.

**Comment by hlb** [comment]
https://github.com/InfuseAI/piperider/pull/324

**Comment by hlb** [comment]
https://github.com/InfuseAI/piperider/pull/314

**Comment by hlb** [comment]
https://github.com/InfuseAI/piperider/pull/310

**Comment by hlb** [comment]
released in https://github.com/InfuseAI/piperider/releases/tag/v0.5.0
